# Generated by Django 3.1.7 on 2021-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=50)),
                ('tw_link', models.URLField()),
                ('fb_link', models.URLField()),
                ('inst_link', models.URLField()),
            ],
        ),
    ]
