# Generated by Django 3.1.7 on 2021-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20210325_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
